# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "nibabel" %}
{% set version = "2.3.3" %}
{% set sha256 = "556a233fdc02045e41f55e877a05dbf5a037d1fa6605909f98a3ab194368a9cb" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    noarch: python
    number: 1
    script: "{{ PYTHON }} -m pip install . -vv"
    entry_points:
      - parrec2nii   = nibabel.cmdline.parrec2nii:main
      - nib-ls       = nibabel.cmdline.ls:main
      - nib-dicomfs  = nibabel.cmdline.dicomfs:main
      - nib-nifti-dx = nibabel.cmdline.nifti_dx:main
      - nib-tck2trk  = nibabel.cmdline.tck2trk:main
      - nib-trk2tck  = nibabel.cmdline.trk2tck:main
      - nib-diff     = nibabel.cmdline.diff:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - h5py
    - pydicom
    - six
    - bz2file

test:
  imports:
    - nibabel
  commands:
    - command -v parrec2nii
    - command -v nib-ls
    - command -v nib-dicomfs
    - command -v nib-nifti-dx
    - command -v nib-tck2trk
    - command -v nib-trk2tck
    - command -v nib-diff


about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
    - grlee77
    - effigies
