{% set version = "2.1.0" %}

package:
  name: nibabel
  version: {{ version }}

source:
  fn: nibabel-{{ version }}.tar.gz
  url: https://github.com/nipy/nibabel/archive/{{ version }}.tar.gz
  md5: f6e213894939aece4619e3a45259dfbd

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - h5py
    - pydicom
  run:
    - python
    - numpy
    - scipy
    - h5py
    - pydicom

test:
  imports:
    - nibabel

about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
