travis:
  secure:
    BINSTAR_TOKEN: PkmzWUrSRFf2GSRbXbhzxMH5TihUBjbxXxixLtuvjXlVtc1eK3I+nJTqF5nMeN7wXJQdOGGciSx1QlHHULHGStUTL4gSwGWMrRdoYyU491MPuN24T7xVSiTLg8P60D8yJJvfvzliokMJkdvz8Q17+WGBQv8GSQMj1RzSdBRKjZgrG+z13qPnaeFYKNfEl+lXastT7aMYEJ4wZfo9CtgP8nw1kFysbPb1lRWYuEpLJy0ck+G+lp974pPZo+7wRPJp0JI6e2ivNb9680hiXHqBf/S4xDzRMFCTVFA4RoBh6eKjWQ+HWETW0rHxlHh/6IPcC4FlaSTk/P44EwbRVRKmcJ8K4CeFa9vBDEigpMfiXqddNuMdhMFiiOMFR3qi+QGUZ7Su+7MzSvT+XTlMenhjWsLigtawMcxyf3PUvS4GKKxwZm2Gi4otJQimMxorCjpEJVkc9tJJq4HCs9ObsKl6BQvZcSNJmWiC5i2BDNkBtVXR3q/Oh2TdNsilYmbygAQ0dOIPhEa4uWhG5Jc+w4KeYWxzYSqojpsUDlqh8FUIYRVb3U2BQ72Iz7bloaluFSLjENC3co2J6y1XI2Gfp6fIaUVKVJJMD0lrWqtrmlbpUKR63riY8LJQZSEkUCr0mDSbZ18PUJc5SVEkNGaE54KnOrh1WjFj66px9HH9pq9ycR0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
